#!/usr/bin/env bash
# Programs that will run after Openbox has started
echo "Starting OpenBox..."
xsetroot -solid black -cursor_name left_ptr &
if [ -e /startapp.sh ]; then
	echo "Starting X app..."
 	exec /startapp.sh &
fi
